version: '3.4'

services:
  dao_votedb: 
    ports:
      - 3312:3306
 
  dao_reputationdb: 
    ports:
      - 3313:3306

  dao_votingengine: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8897:80"

  dao_reputationservice: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8898:80"