version: '3.4'

volumes:
  vote_datafiles:
  reputation_datafiles:

services:
  dao_rabbitmq:
    image: rabbitmq:3-management
    container_name: 'dao_rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: "daorabbit"
        RABBITMQ_DEFAULT_PASS: "dao2021*"
    ports:
        - 5673:5673
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/lib/log
    healthcheck:
        test: rabbitmq-diagnostics -q status
        interval: 10s
        timeout: 30s
        retries: 15
    
    networks:
        - daonetwork

  dao_votedb:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - vote_datafiles:/var/lib/mysql      
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secred
      - MYSQL_DATABASE=daovotedb
    networks:
      - daonetwork  

  dao_reputationdb:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - reputation_datafiles:/var/lib/mysql      
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secred
      - MYSQL_DATABASE=daoreputationdb
    networks:
      - daonetwork  

  dao_votingengine:
    image: ${DOCKER_REGISTRY-}daovotingengine
    build:
      context: .
      dockerfile: DAO_VotingEngine/Dockerfile
    depends_on:      
      dao_rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - daonetwork

  dao_reputationservice:
    image: ${DOCKER_REGISTRY-}daoreputationservice
    build:
      context: .
      dockerfile: DAO_ReputationService/Dockerfile
    depends_on:      
      dao_rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - daonetwork
networks:
  daonetwork:
    name: daonetwork
    driver: bridge







